### ISSUE TITLE
How to use it together with a vertical photo?

### ISSUE THREAD

**Issue by coalus** [elyha7/yoloface#4]
Hi!
Firstly, thank you so much for such a convenient wrapper, you saved a lot of time, thank you again!
When trying to "drive away" a vertical photo, unfortunately I encounter an error

RuntimeError: Given groups=1, weight of size [32, 3, 3, 3], expected input[1, 4, 608, 608] to have 3 channels, but got 4 channels instead

I will be glad to help, thanks a lot in advance!
Have a nice day :D

**Comment by elyha7** [comment]
Model works fine with vertical photos. In your case, you probably have RGBA image with 4 channels instead of RGB with 3 channels. Try something like this to convert you image to rgb:
```python
from PIL import Image
import numpy as np

rgba_image = Image.open(path_to_image)
rgb_image = rgba_image.convert('RGB')
image_numpy = np.array(rgb_image)
```

**Comment by coalus** [comment]
Ok, спасибо большое за столь быстрый ответ, глупейший вопрос задал, еще раз большое спасибо!
